# Set target Python version for syntax compatibility
target-version = "py311"

line-length = 100

[lint]
# Enable useful lint rules for maintainability and consistency
select = [
  "F",    # Pyflakes: undefined names, unused imports, etc.
  "E",    # pycodestyle: indentation and whitespace
  "W",    # pycodestyle: warnings
  "I",    # isort: import sorting
  "ANN",  # type annotations (require type hints)
  "C90",  # complexity checks
  "UP",   # pyupgrade: modern Python syntax suggestions
]

# Ignore a few noisy or unnecessary annotation rules
ignore = [
  "ANN204",  # don't require return type for __init__
]

# Allow relaxed typing rules in test files
[lint.per-file-ignores]
"tests/*" = ["ANN"]

[format]
# Formatter configuration for spacing, quoting, and line length
indent-style = "space"
line-ending = "auto"
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 88