from typing import Protocol


class HalInterface(Protocol):
    @property
    def is_machine_on(self) -> bool: ...

    @property
    def is_pressure_ok(self) -> bool: ...

    def activate_pump(self) -> None: ...

    def deactivate_pump(self) -> None: ...

    def activate_error(self) -> None: ...

    def deactivate_error(self) -> None: ...


class StatInterface(Protocol):
    def poll(self) -> None: ...


class CommandInterface(Protocol):
    def text_msg(self, message: str) -> None: ...

    def error_msg(self, message: str) -> None: ...


class IniInterface(Protocol):
    @property
    def is_lubrication_enabled(self) -> bool: ...

    @property
    def pump_interval(self) -> int: ...

    @property
    def pressure_timeout(self) -> int: ...

    @property
    def pressure_hold_time(self) -> int: ...


class Logger(Protocol):
    def info(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
